### ISSUE TITLE
Can your provide the IMU coordinate on platform and the tilt angle of alphasense?

### ISSUE THREAD

**Issue by LarryDong** [ntnu-arl/underwater-datasets#2]
Hi Mohit Singh,
Thanks for sharing the data.
Although in calibration file, IMU to Cam0 is provided, but the reference frame is not clearly shown in figure.

Based on the data, I guess the IMU coordinate is lilke this:
![图片](https://github.com/ntnu-arl/underwater-datasets/assets/14933902/0473f2e1-5341-42b5-9bfe-dd266db60a5f)

However, I want to aligh gravity of IMU to the ground, so can you provide the accurate tilt angle of the IMU?
Or, any static data recorded when the platform is staticly placed on the ground?

Thanks.

**Comment by Mohit505Git** [comment]
Hi @LarryDong,

I hope it is not too late to answer this.

The camera module is pitched down by 16 degrees w.r.t the robot base_link frame.

**Comment by LarryDong** [comment]
> Hi @LarryDong,
> 
> I hope it is not too late to answer this.
> 
> The camera module is pitched down by 16 degrees w.r.t the robot base_link frame.

Thanks for your reply. Never too late.
